### ISSUE TITLE
Only one set of bindings can be reliably used within a single Lua instance

### ISSUE THREAD

**Issue by scooter-dangle** [distil/rust_lua_ffi#9]
Given Rust libs A and B, they cannot be `require`d in the same Lua instance if any of their type names are the same. Note that it's easy to unintentionally run into this restriction since a number of basic 'composite' types (e.g., `Vec<u8>`, `Option<T>`, `Result<T, E>`) will result in structs of the same name passed to `ffi.metatype` even if—in the case of generic types—the generic parameters are primitive C types.

**Comment by Marwes** [comment]
I feel a bit confused. Why is `Vec<u8>` causing a problem. If the two libraries use the same name for it in `ffi.metatype` then that should only matter if that creates two different types *and* the libraries try to send a value between them which would then trigger a type violation.

If `ffi.metatype` generates the same type for both it shouldn't be a problem since they are in fact the same type. Or, if the libraries do not send data directly between them then it is not an issue either since they can't observe what the other does.

**Comment by scooter-dangle** [comment]
I probably didn't explain it very well. I don't know that their having the same type+typename is a _logical_ issue in how the bindings are generated and consumed<sup>1</sup>, but it's an issue given the [restriction on `ffi.metatype`](https://luajit.org/ext_ffi_api.html#ffi_metatype) that

> The association with a metatable is permanent and cannot be changed afterwards. Neither the contents of the `metatable` nor the contents of an `__index` table (if any) may be modified afterwards. The associated metatable automatically applies to all uses of this type, no matter how the objects are created or where they originate from.

Since the `ffi.metatype` declaration is global, any subsequent declaration with an identical string as the first argument (due to a separate set of generated bindings that use the same type) will cause an exception.

1: _Maybe_ it is, but I'm not familiar enough with the implementation of LuaJIT's `ffi` module to say.
